[package]
name = "sshmux"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
colored = "2"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
clap = { version = "4.5.39", features = ["derive"] }
